---
kind: pipeline
type: docker
name: test-linux-amd64

platform:
  os: linux
  arch: amd64

# Pipeline is executed only on master branch
trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: Backend-Test
    pull: always
    image: golang:1.15
    commands:
      - make test
    volumes:
      - name: cache
        path: /go/pkg

  - name: pushover
    image: plugins/pushover
    settings:
      user:
        from_secret: pushover_user
      token:
        from_secret: pushover_token


---
kind: pipeline
type: docker
name: build-linux-amd64

platform:
  os: linux
  arch: amd64

# Pipeline is executed only on tag push
trigger:
  ref:
    - refs/tags/*

steps:


  - name: Service-Publish
    image: plugins/docker
    settings:
      auto_tag: true
      registry: repo.treescale.com
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: pushover
    image: plugins/pushover
    settings:
      user:
        from_secret: pushover_user
      token:
        from_secret: pushover_token
