---
kind: pipeline
type: docker
name: test-linux-amd64

platform:
  os: linux
  arch: amd64

# Pipeline is executed only on master branch
trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: Backend-Test
    pull: always
    image: golang:1.15
    commands:
      - make test
    volumes:
      - name: cache
        path: /go/pkg

  - name: pushover
    image: plugins/pushover
    settings:
      user:
        from_secret: pushover_user
      token:
        from_secret: pushover_token


---
kind: pipeline
type: docker
name: build-linux-amd64

platform:
  os: linux
  arch: amd64

# Pipeline is executed only on tag push
trigger:
  event:
    - tag

steps:
  - name: Docker-Build
    image: plugins/docker
    settings:
      auto_tag: true
      repo:
        from_secret: docker_repo
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

---
kind: pipeline
type: docker
name: deploy-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy
    image: docker:latest
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - env
#      - docker service update --image {DRONE_REPO}:{SERVICE_TAG} {SERVICE}

trigger:
  event:
    - promote
  target:
    - production

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
