name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.17' ]

    steps:
      - uses: actions/checkout@v2

      - name: Go ${{ matrix.go }} test
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: make test